security:
    # See https://symfony.com/doc/current/security.html for more details.
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # firewallls define how users are authenticated and how to handle unauthenticated requests
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
            #Routes d'accès pour les différentes parties de l'API
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
            #Route d'inscription accessible à tous
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
            #Docs de l'API accessibles à tous
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
            #Admin uniquement pour la gestion des utilisateurs
        - { path: ^/api/users$, roles: ROLE_ADMIN, methods: [GET] }
        #utilisateurs spécifiques accessibles à l'admin pour la gestion
        - { path: ^/api/users, roles: ROLE_ADMIN, methods: [GET, PUT, DELETE] }
            #Toutes les autres routes de l'API nécessitent une authentification complète
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
