security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        # Login JWT
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

        # Firewall pour les routes API sécurisées  API
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

        #Firewall pour la déconnexion
        logout:
            pattern: ^/api/logout
            stateless: true
            
        # Firewall obligatoire même si non utilisé
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        # Autoriser login
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin uniquement
        - { path: ^/api/users$, roles: ROLE_ADMIN }

        # Toutes les autres routes API nécessitent un token
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
